title: "Ali Zamani"
author: "Ali Zamani"
description: " "
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home", icon: home}
  - {file: "CV.md", title: "my CV", icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:ali-zamani@live.com"}
  - {title: Github, icon: github, url: "https://github.com/alizmni"}
  - {title: Google Scholar, icon: google, url: "https://scholar.google.com/citations?user=4iDc7pMAAAAJ&hl=en"}
  - {title: LinkedIn, icon: linkedin, url: "https://linkedin.com/in/ali-zamani-76b1234b"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
